### ISSUE TITLE
Logo overhangs on login page on laptop

### ISSUE THREAD

**Issue by ChristopherKingChemist** [dbnschools/moodle-theme_fordson#53] opened 2018-12-08 19:09 UTC
On my login page the login box uses a logo.  The logo overhangs the box a small amount on my laptop, as shown below.
![image](https://user-images.githubusercontent.com/34283059/49689637-83c74a00-fae9-11e8-9df6-f311c23d1f05.png)
The laptop's resolution is 1366 × 768.  The logo's size is 874 × 276.  On my larger monitor at work the logo has scaled nicely.  
Thanks for the wonderful theme!

**Comment by dbnschools** [comment] 2018-12-10 15:09
Hello Chris,
Do you have a URL I can see what this looks like.  I want to see the page so I might better understand what's going on.

**Comment by ChristopherKingChemist** [comment] 2018-12-10 16:05
The site is https:// christopherking dot name backslash collaborate backslash
( I don't want it indexed by search engines, yet.)
The logo does not appear to scale when the Firefox window size is changed, regardless of the size of the monitor.
Using Moodle 3.6.1, Firefox, the latest Jordson, theme preset "Spectrum-achromatic", course tile display "Tile Style Four W/Course Summary".

**Comment by ChristopherKingChemist** [comment] 2018-12-10 16:09
Sorry; didn't mean to close this.

**Comment by dbnschools** [comment] 2018-12-10 16:24
Perfect.  I see where the issue is and have a fix.  I just posted a new version of Fordson today, so this will be included in the next release but I will tell you how to change it if you want ahead of the next release.  You can add this to the line 205 of a template file and it will fix the issue: class="img-fluid"

https://github.com/dbnschools/moodle-theme_fordson/blob/master/templates/core/loginform.mustache#L205
Change the line in the link above to this:  
`<h2 class="card-header text-center" ><img src="{{logourl}}" class="img-fluid" title="{{sitename}}" alt="{{sitename}}"/></h2>`
Note how I added the class="img-fluid" as that is the code that fixes the image issue on the login page.  This will be included in the next release.  Thanks for identifying the problem.

**Closed** 2018-12-10 16:25 UTC
